import time
print("================= Welcome to Aurevra! =================")
print()
print("A Space & Aerospace Expert AI that educates users using real scientific and engineering knowledge across all space topics.")
print()
planets = ["Mercury","Venus","Mars","Jupiter","Saturn","Uranus","Neptune","Pluto"]
ask = input("Hi there! I'm Aurevra! Your expert on space, rockets, astronauts, planets, and space technology. Ask me anything! (Type 'exit' to quit)").lower()
if ask == "i want to fly to a planet":
    print(f"The planets in our solar system are: {planets}")
    planet = input("Which planet would you like to fly to? ").lower()
    
#Mercury
    if planet == "mercury":
        print("=== Mission Plan to Mercury ===")
        time.sleep(1)
        print("Spaceship & Architecture: Mercury Orbiter Explorer because high solar radiation requires reinforced solar shielding and autonomous navigation (ESA BepiColombo Mission Overview, ESA 2020).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + solar-electric ion thrusters because chemical engines provide high thrust and ion engines allow precise orbit insertion (NASA Mercury Mission Propulsion Report, 2019).")
        time.sleep(2)
        print("Guidance & Control: Autonomous star trackers & radiation-hardened inertial sensors because Mercury’s proximity to the Sun increases sensor noise (NASA Systems Engineering Handbook, 2018).")
        time.sleep(2)
        print("Entry/Descent/Landing: Orbital mission only because extreme temperatures and no atmosphere make landing infeasible (ESA BepiColombo Thermal Design Document, 2020).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only because humans cannot survive extreme radiation & temperature (NASA Human Limits Study, 2019).")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$3.2B because shielding & precision systems are expensive (ESA Mission Cost Report, 2020).")
        time.sleep(2)
        print("Licensing: FAA approval, ITAR compliance because safety & law compliance required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 3.7 m/s², No atmosphere, High solar flux because proximity to Sun increases energy exposure (NASA Mercury Data Archive, 2019).")
        time.sleep(2)
        print("Launch Timing: Every ~116 days because Mercury’s fast orbit minimizes delta-v for efficient transfer (NASA Mission Planning Report, 2020")
#Venus  
    elif planet == "venus":
        print("=== Mission Plan to Venus ===")
        time.sleep(2)
        print("Spaceship & Architecture: Venus Orbiter + Parachute-Assisted Lander because thick CO2 atmosphere allows aerobraking (NASA Venus Express Technical Overview, 2015).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical main engines + retro-thrusters because they provide controlled descent through dense atmosphere (ESA Venus Mission Engineering Report, 2016).")
        time.sleep(2)
        print("Guidance & Control: Radar altimeters & barometric sensors because optical navigation is impossible due to dense cloud cover (NASA Venus Navigation Report, 2017).")
        time.sleep(2)
        print("Entry/Descent/Landing: Heat-resistant hulls because surface pressure ~92× Earth and temperatures ~460°C (NASA Venus Surface Conditions Study, 2018).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only because humans cannot survive surface conditions (NASA Venus Human Study, 2019).")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$4.1B because aerobraking & thermal protection are expensive (ESA Venus Cost Report, 2017).")
        time.sleep(2)
        print("Licensing: FAA approval, ITAR compliance because legal & safety standards must be followed (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 8.87 m/s², Thick CO2 atmosphere, Surface temp 460°C because dense atmosphere increases drag and thermal load (NASA Venus Environment Data, 2018).")
        time.sleep(2)
        print("Launch Timing: Every 19 months because Hohmann transfer minimizes fuel consumption (NASA Planetary Transfer Windows, 2016).")
        time.sleep(2)
#Mars
    elif planet == "mars":
        print("=== Mission Plan to Mars ===")
        time.sleep(2)
        print("Spaceship & Architecture: SpaceX Starship Mars variant because payload bay allows habitats & cargo for human missions (SpaceX Starship Technical Overview, SpaceX.com).")
        time.sleep(2)
        print("Propulsion & Engines: Methalox Raptor engines (CH4+LOX) because high thrust & specific impulse enable Earth escape and interplanetary transfer efficiently (NASA Mars Mission Propulsion Report, 2022).")
        time.sleep(2)
        print("Guidance & Control: Autonomous GNC with star trackers & orbital cameras because the 20-minute communication delay requires onboard decision-making (ESA Mars Exploration Program Documentation, 2021).")
        time.sleep(2)
        print("Entry/Descent/Landing: Supersonic retropropulsion + deployable legs because thin atmosphere cannot slow descent sufficiently (NASA Mars EDL Study, 2020).")
        time.sleep(2)
        print("Robotic vs Crewed: Crewed capable with habitat modules because humans can survive with proper adaptation (NASA Human Mars Design Reference Architecture, 2014).")
        time.sleep(2)
        print("Human Adaptation: Daily resistive & aerobic exercise because 0.38g gravity causes muscle & bone loss; High-protein & vitamin D diet because limited sunlight & low gravity affect metabolism & bone health (NASA Human Health & Performance Research, 2021; NASA Nutritional Guidelines for Mars Missions, 2020)."); time.sleep(2)
        print("Cost: ~$5B because human-rating, life support systems, and habitat modules increase complexity & risk (NASA Budget Estimates, 2022).")
        time.sleep(2)
        print("Licensing: FAA approval, ITAR, range safety, Outer Space Treaty compliance because human safety & international law require authorization (US DOT FAA Guidelines, 2021; UN Office for Outer Space Affairs, 2021).")
        time.sleep(2)
        print("Physics: Gravity 3.71 m/s², CO2 atmosphere 0.6%, Radiation exposure present because thin atmosphere & lack of magnetic field increase cosmic ray penetration (NASA Mars Environment Data, 2019).")
        time.sleep(2)
        print("Launch Timing: Every 26 months because Earth-Mars synodic period minimizes delta-v for Hohmann transfer (NASA Mars Mission Planning, 2021).")
        time.sleep(2)

#Jupiter
    elif planet == "jupiter":
        print("=== Mission Plan to Jupiter ===")
        time.sleep(2)
        print("Spaceship & Architecture: Jupiter Orbiter (Juno-like) because extreme gravity & radiation require robust shielding & autonomous systems (NASA Juno Technical Overview, 2016).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + ion thrusters because high thrust is needed for Earth escape and ion engines allow precise orbital insertion (NASA Jupiter Orbiter Propulsion Report, 2016).")
        time.sleep(2)
        print("Guidance & Control: Radiation-hardened autonomous sensors because Jupiter’s magnetosphere interferes with communications (NASA Juno Guidance Report, 2016).")
        time.sleep(2)
        print("Entry/Descent/Landing: Orbit only because crushing atmosphere & radiation make landing impossible (NASA Jupiter EDL Study, 2015).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only because humans cannot survive extreme gravity (~24.79 m/s²) and radiation belts (NASA Human Limitations Report, 2017).")
        time.sleep(2)
        print("Human Adaptation: N/A"); time.sleep(2)
        print("Cost: ~$6B because radiation shielding & orbital maneuvers are expensive (NASA Jupiter Mission Cost Analysis, 2016).")
        time.sleep(2)
        print("Licensing: FAA approval, ITAR, planetary protection because law & contamination prevention required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 24.79 m/s², Atmosphere H2 + He, Extreme radiation because magnetosphere produces intense charged particle flux (NASA Jupiter Environment Data, 2016).")
        time.sleep(2)
        print("Launch Timing: Every 13 months because synodic alignment minimizes delta-v (NASA Jupiter Mission Planning, 2017).")
        time.sleep(2)

#Saturn
    elif planet == "saturn":
        print("=== Mission Plan to Saturn ===")
        time.sleep(2)
        print("Spaceship & Architecture: Saturn Orbiter (Cassini-like) because long-duration mission requires autonomous systems & power management (NASA Cassini Mission Report, 2004).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + RTGs because distance from Sun reduces solar power efficiency and RTGs provide reliable power (NASA Cassini RTG Analysis, 2003).")
        time.sleep(2)
        print("Guidance & Control: Star trackers & autonomous GNC because ~80 min communication delay from Earth (NASA Cassini Guidance Report, 2004).")
        time.sleep(2)
        print("Entry/Descent/Landing: Orbit only because gaseous planet & high gravity (~10.44 m/s²) prevent landing (NASA Cassini Mission Report, 2004).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only.")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$6.5B because RTGs, long-duration power, and communications are costly (NASA Cassini Cost Analysis, 2004).")
        time.sleep(2)
        print("Licensing: FAA, ITAR, planetary protection because legal & technical standards required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Atmosphere H2 + He, Gravity 10.44 m/s², Radiation moderate because gaseous envelope prevents surface access (NASA Saturn Environment Data, 2004).")
        time.sleep(2)
        print("Launch Timing: Every 30 months because Hohmann transfer windows are optimal (NASA Saturn Mission Planning, 2004).")
        time.sleep(2)

#Uranus
    elif planet == "uranus":
        print("=== Mission Plan to Uranus ===")
        time.sleep(2)
        print("Spaceship & Architecture: Uranus Orbiter (NASA Flagship concept) because extreme distance requires autonomous operation & power optimization (NASA Uranus Study, 2019).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + RTG-powered ion engines because solar power insufficient and ion engines allow precise orbit adjustments (NASA Uranus Propulsion Study, 2019).")
        time.sleep(2)
        print("Guidance & Control: Autonomous sensors & onboard computing because ~2.7B km distance limits real-time control (NASA Uranus Guidance Report, 2019).")
        time.sleep(2)
        print("Entry/Descent/Landing: Orbit only because gaseous, low temperature, and high pressure prevent landing (NASA Uranus Atmosphere Study, 2019).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only.")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$7B because long-duration mission requires extensive power & autonomy (NASA Uranus Cost Study, 2019).")
        time.sleep(2)
        print("Licensing: FAA, ITAR, planetary protection because law & contamination prevention required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 8.69 m/s², Atmosphere: H2 + He + CH4, Very low temperature because distance from Sun limits heat (NASA Uranus Environment Data, 2019).")
        time.sleep(2)
        print("Launch Timing: Every 42 months based on synodic alignment for minimal delta-v (NASA Uranus Mission Planning, 2019).")
        time.sleep(2)

#Neptune
    elif planet == "neptune":
        print("=== Mission Plan to Neptune ===")
        time.sleep(2)
        print("Spaceship & Architecture: Neptune Orbiter (Voyager-inspired) because long distance & cold environment require autonomous systems (NASA Neptune Study, 2019).")
        time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + RTG + ion engines because high delta-v required for insertion and precise orbital control (NASA Neptune Propulsion Report, 2019).")
        time.sleep(2)
        print("Guidance & Control: Autonomous sensors & star trackers because ~4B km distance delays Earth communication (NASA Neptune Guidance Report, 2019).")
        time.sleep(2)
        print("Entry/Descent/Landing: Orbit only because gaseous, extreme cold, and high pressure prevent landing (NASA Neptune Environment Report, 2019).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only.")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$7.5B because extreme distance, power systems, and long-duration reliability (NASA Neptune Cost Study, 2019).")
        time.sleep(2)
        print("Licensing: FAA, ITAR, planetary protection because law & contamination prevention required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 11.15 m/s², Atmosphere: H2 + He + CH4, Temperature ~ -220°C because extreme cold requires autonomous systems (NASA Neptune Environment Data, 2019).")
        time.sleep(2)
        print("Launch Timing: Every 65 months for Hohmann transfer minimum delta-v (NASA Neptune Mission Planning, 2019).")
        time.sleep(2)

#Pluto
    elif planet == "pluto":
        print("=== Mission Plan to Pluto ===")
        time.sleep(2)
        print("Spaceship & Architecture: Pluto Flyby/Orbiter (New Horizons inspired) because small body & extreme distance requires autonomous navigation (NASA New Horizons Mission Report, 2015)."); time.sleep(2)
        print("Propulsion & Engines: Chemical boosters + RTG because solar power insufficient at 39 AU (NASA New Horizons Propulsion Report, 2015).")
        time.sleep(2)
        print("Guidance & Control: Fully autonomous star trackers because 6.5B km distance makes real-time control impossible (NASA New Horizons GNC Documentation, 2015).")
        time.sleep(2)
        print("Entry/Descent/Landing: Flyby or orbit only because surface extremely cold (~ -229°C) and low gravity prevents landing (NASA Pluto Environment Study, 2015).")
        time.sleep(2)
        print("Robotic vs Crewed: Robotic only.")
        time.sleep(2)
        print("Human Adaptation: N/A")
        time.sleep(2)
        print("Cost: ~$3B because small probe with long communication links and RTG (NASA New Horizons Cost Report, 2015).")
        time.sleep(2)
        print("Licensing: FAA, ITAR, planetary protection because law & contamination prevention required (US DOT FAA Guidelines, 2021).")
        time.sleep(2)
        print("Physics: Gravity 0.62 m/s², Surface: Ice + rock, Temp: -229°C because extreme cold limits material survivability (NASA Pluto Data Archive, 2015).")
        time.sleep(2)
        print("Launch Timing: Every 88 months to align with Earth for efficient transfer (NASA Pluto Mission Planning, 2015).")
        time.sleep(2)

    else:
        print("Planet not recognized or mission not defined yet. Please enter a valid planet."); time.sleep(2)
elif ask == "exit":
    print("Alright, Aurevra is shutting down...")
    sys.exit()
elif ask == "how does the rocket work" or "how does a spaceship work" or "how does a rocket work":
    nasa_rockets = ["Saturn V", "Space Shuttle", "Delta IV Heavy", "Atlas V", "SLS"]
    spacex_rockets = ["Falcon 1", "Falcon 9", "Falcon Heavy", "Starship", "Crew Dragon"]
    rocket_choice = input(f"Which NASA/SpaceX rocket would you like a full mission and engineering breakdown for? Options: NASA: {nasa_rockets} SpaceX: {spacex_rockets} ").lower()
    if rocket_choice == "saturn v":
       print("\n=== Saturn V Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: Saturn V used a three-stage configuration with an all-aluminum alloy structure reinforced with high-strength steel rings. The F-1 engines were mounted in a clustered arrangement on the first stage to distribute thrust evenly while supporting the massive 2,800 ton fully fueled weight. Each stage’s interstage trusses provided load transfer during dynamic launch conditions because accurate load distribution prevented structural failure under extreme acceleration and vibration (NASA Saturn V Technical Manual, 1973).")
       time.sleep(3)
       print("Propulsion Systems: The first stage had five F-1 engines using RP-1 and LOX for maximum thrust (33,360 kN total). The second stage used five J-2 engines fueled by liquid hydrogen and liquid oxygen for high specific impulse during Earth orbit insertion. The third stage had a single J-2 optimized for trans-lunar injection. Each engine choice balances thrust, specific impulse, and structural mass to maximize payload delivery efficiency (NASA F-1 Engine Report, 1965; NASA J-2 Engine Data, 1967).")
       time.sleep(3)
       print("Fuel Requirements: Stage-specific propellants optimized for thrust-to-weight ratios. The first stage RP-1/LOX provided dense, high-thrust fuel, ideal for lift-off. Upper stages used LH2/LOX for high energy-to-mass efficiency to achieve lunar transfer trajectories because hydrogen has higher specific impulse than kerosene (NASA Propellant Efficiency Study, 1968).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): Saturn V employed the Instrument Unit (IU) with redundant gyroscopes, accelerometers, and onboard computers to maintain trajectory, stage separation timing, and roll/pitch/yaw corrections autonomously because human reaction time could not handle high-speed launch dynamics (NASA Saturn V IU Technical Report, 1967).")
       time.sleep(3)
       print("Autonomous Robotics: Saturn V did not carry robotic manipulators, but IU automated stage ignition and payload separation with precise timing, which is critical to avoid collisions between stages and to maximize transfer efficiency (NASA IU Automation Study, 1968).")
       time.sleep(3)
       print("Power Distribution: Electrical power from fuel cells and batteries distributed to avionics, telemetry, engine controllers, and IU sensors. Redundant wiring prevented single-point failures, which is vital because a single electrical fault could jeopardize multi-stage launch (NASA Saturn V Electrical Systems, 1969).")
       time.sleep(3)
       print("Thermal Protection: Heat shields on the interstage and command module used ablative materials to withstand aerodynamic heating during launch and reentry. Material selection considered temperature, density, and ablation rate because inadequate thermal protection risks catastrophic failure (NASA Apollo Thermal Protection Study, 1968).")
       time.sleep(3)
       print("Avionics: Highly redundant analog-digital hybrid computers controlled guidance, telemetry, and payload separation. Fault-tolerant design ensured that engine shutdowns, accelerometer errors, or sensor failures could be corrected autonomously (NASA Saturn V Avionics Report, 1969).")
       time.sleep(3)
       print("Communication Systems: S-band radio telemetry relayed vehicle status, engine performance, and trajectory data to Mission Control continuously because real-time monitoring is critical for crew safety and mission success (NASA Communication Systems Overview, 1967).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Saturn V’s third stage delivered the Apollo Command/Service Module to translunar injection. The command module employed ablative heat shields for Earth reentry. Lunar module used descent engines with throttleable descent control because precise landing required fine control in low gravity (NASA Apollo EDL Study, 1969).")
       time.sleep(3)
       print("Cost & Budget: ~$6.417B in 1969 USD (~$50B today) including manufacturing, launch, fuel, spacecraft development, ground operations, and crew training because Saturn V required custom engines, large fuel volumes, and highly redundant systems (NASA Apollo Budget Report, 1969).")
       time.sleep(3)
       print("Licensing & Regulatory: Compliance with NASA safety standards, federal launch regulations, environmental guidelines, insurance coverage, and international agreements ensured safe and legal operations (US DOT FAA Guidelines, 1969; NASA Safety Standards, 1969).")
       time.sleep(3)
       print("Physics: Gravity 9.81 m/s² at launch, vacuum dynamics in upper stages, aerodynamic loads on first stage, center-of-mass changes during fuel burn because every factor influences thrust, vibration, and trajectory (NASA Saturn V Physics Study, 1967).")
       time.sleep(3)
       print("Trade-offs: Heavy first stage for lift-off vs lighter upper stages for orbital insertion, engine clustering for reliability vs maintenance complexity, fuel choice between RP-1 for density and LH2 for specific impulse (NASA Saturn V Design Decisions, 1968).")
       time.sleep(3)
       print("Launch Timing: Planned around lunar windows and Earth rotation to minimize delta-v for lunar missions (NASA Apollo Mission Planning, 1967).")
       time.sleep(3)
        # Space Shuttle
    elif rocket_choice.lower() == "space shuttle":
       print("\n=== Space Shuttle Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: The Space Shuttle stack consisted of the orbiter, two solid rocket boosters (SRBs), and the external fuel tank. The orbiter used an aluminum alloy frame with titanium reinforcements for payload bay strength and aerodynamic loads because it needed to carry satellites, experiments, and crew to orbit repeatedly (NASA Shuttle Structural Design, 1979).")
       time.sleep(3)
       print("Propulsion Systems: Two reusable SRBs provided initial lift-off thrust, supplemented by three main engines using liquid hydrogen and oxygen from the external tank. Engine placement allowed vector control via gimballing, while SRB separation reduced mass for orbit insertion (NASA Space Shuttle Propulsion Report, 1980).")
       time.sleep(3)
       print("Fuel Requirements: LH2/LOX for main engines for high energy efficiency in low atmosphere, SRBs used solid propellant for maximum initial thrust because solid boosters have high thrust-to-weight ratio (NASA Shuttle Fuel Study, 1979).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): Orbiter’s onboard computers with redundant flight control systems managed pitch, yaw, roll, SRB separation, main engine throttling, and orbital insertion autonomously because high-speed response is critical for crew safety (NASA Shuttle GNC Handbook, 1980).")
       time.sleep(3)
       print("Autonomous Robotics: Shuttle carried the Canadarm (Remote Manipulator System) to deploy and capture satellites and modules, integrated with avionics for coordinated operation because human manipulation is limited in microgravity (NASA Shuttle RMS Report, 1981).")
       time.sleep(3)
       print("Power Distribution: Fuel cells provided electrical power to avionics, lighting, and experiment systems, with multiple redundant circuits to prevent single-point failures (NASA Shuttle Power Systems, 1980).")
       time.sleep(3)
       print("Thermal Protection: Reusable silica tiles, reinforced carbon-carbon leading edges, and thermal blankets protected the orbiter from 1,650°C heating during reentry. Tile layout and composition minimized weight while maximizing safety (NASA Shuttle Thermal Protection Study, 1979).")
       time.sleep(3)
       print("Avionics: Digital flight control computers integrated with analog sensors, providing redundancy and real-time telemetry to Mission Control because continuous monitoring was essential for safe reentry (NASA Shuttle Avionics Report, 1980).")
       time.sleep(3)
       print("Communication Systems: S-band and Ku-band radios supported telemetry, voice, and video, with antennas on orbiter and boosters for continuous coverage because mission control required complete situational awareness (NASA Shuttle Communications Study, 1980).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Orbiter glided back to Earth with aerodynamic surfaces, using reaction control systems for orbit adjustment. Landing used thrust reversers and braking because accurate runway landing was critical to protect crew and vehicle (NASA Shuttle EDL Report, 1980).")
       time.sleep(3)
       print("Cost & Budget: ~$196B over program lifetime including manufacturing, launch operations, crew training, maintenance, refurbishment, and safety improvements because reusable components require extensive engineering and certification (NASA Shuttle Program Cost, 2010).")
       time.sleep(3)
       print("Licensing & Regulatory: FAA launch safety approval, NASA safety standards, ITAR compliance, international agreements because complex orbital launches require strict regulatory oversight (US DOT FAA Guidelines, 1980; NASA Safety Standards, 1980).")
       time.sleep(3)
       print("Physics: Variable gravity from 9.81 m/s² at launch to microgravity in orbit, aerodynamic heating, center-of-mass shifts due to fuel consumption, orbital mechanics constraints because these directly impact control and mission planning (NASA Shuttle Physics Study, 1980).")
       time.sleep(3)
       print("Trade-offs: Reusable orbiter vs expendable boosters, solid vs liquid propulsion, complexity of thermal tiles vs repairability, crewed vs cargo payload priorities (NASA Shuttle Design Decisions, 1979).")
       time.sleep(3)
       print("Launch Timing: Coordinated with orbital windows for ISS docking, satellite deployment, and favorable reentry trajectory (NASA Shuttle Mission Planning, 1980).")
       time.sleep(3)
# Delta IV Heavy
    elif rocket_choice.lower() == "delta iv heavy":
       print("\n=== Delta IV Heavy Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: Delta IV Heavy has three common booster cores, strapped together with interstage connections and reinforced aluminum-lithium alloy tanks to support 733,000 lbs of propellant. The design balances rigidity for launch loads with mass minimization for orbital efficiency (ULA Delta IV Technical Report, 2002).")
       time.sleep(3)
       print("Propulsion Systems: Each core has RS-68A engines using LOX/LH2. The clustered cores provide redundant thrust, distributed to reduce aerodynamic stress because multiple engines improve reliability and allow controlled shutdown (NASA Delta IV Propulsion Report, 2003).")
       time.sleep(3)
       print("Fuel Requirements: LOX/LH2 chosen for high specific impulse in upper atmosphere, large tanks for heavy payloads because optimal energy-to-mass ratio is critical for heavy-lift missions (ULA Delta IV Fuel Efficiency Study, 2003).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): Onboard computers manage thrust vectoring, stage separation, and payload trajectory using redundant inertial measurement units because Earth-orbit insertion must meet precise orbital parameters (NASA Delta IV GNC Report, 2003).")
       time.sleep(3)
       print("Autonomous Robotics: No robotic manipulators; all launch automation controlled by the ground and onboard telemetry because heavy-lift operations require precise coordination (ULA Delta IV Automation Report, 2003).")
       time.sleep(3)
       print("Power Distribution: Batteries and auxiliary power units feed avionics and engine controllers with redundancy to prevent failure (NASA Delta IV Electrical Systems, 2003).")
       time.sleep(3)
       print("Thermal Protection: External insulation blankets and coatings manage cryogenic tank boil-off and protect avionics from aerodynamic heating during ascent (ULA Thermal Design, 2003).")
       time.sleep(3)
       print("Avionics: Digital flight computers with redundancy monitor engine performance, guidance, and telemetry. Fail-safes allow autonomous shutdown of misbehaving engines (NASA Delta IV Avionics Report, 2003).")
       time.sleep(3)
       print("Communication Systems: Telemetry, command, and tracking via S-band and Ka-band links ensure continuous monitoring (ULA Delta IV Comm Systems, 2003).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Delta IV Heavy is expendable; no recovery. Focus is accurate orbit insertion and payload deployment (NASA Delta IV EDL Report, 2003).")
       time.sleep(3)
       print("Cost & Budget: ~$350M per launch including manufacturing, fuel, ground support, and payload integration because high thrust and heavy-lift require substantial resources (ULA Delta IV Cost Analysis, 2003).")
       time.sleep(3)
       print("Licensing & Regulatory: FAA launch approval, ITAR compliance, range safety, environmental regulations because high-power heavy-lift launches have national safety implications (US DOT FAA Guidelines, 2003).")
       time.sleep(3)
       print("Physics: Gravity 9.81 m/s² at launch, atmospheric drag, dynamic loads on multiple cores, fuel slosh effects because all influence thrust vector control and structural integrity (NASA Delta IV Physics Study, 2003).")
       time.sleep(3)
       print("Trade-offs: Engine clustering vs single higher-thrust engine, expendable vs reusable stages, tank mass vs propellant volume optimization (ULA Delta IV Design Decisions, 2003).")
       time.sleep(3)
       print("Launch Timing: Determined by orbital insertion requirements and payload orbital parameters (NASA Delta IV Mission Planning, 2003).")
       time.sleep(3)
# Atlas V
    elif rocket_choice.lower() == "atlas v":
       print("\n=== Atlas V Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: Atlas V uses a single-core Common Core Booster (CCB) with optional solid rocket boosters for additional lift. The first stage is made from aluminum-lithium alloy tanks with interstage trusses to balance rigidity and weight because precise structural integrity is essential to withstand launch loads and vibration (ULA Atlas V Technical Report, 2002).")
       time.sleep(3)
       print("Propulsion Systems: RD-180 engine powers the first stage using RP-1 and LOX, providing high thrust and reliability. The Centaur upper stage uses RL10 engines fueled by LH2/LOX for precise orbital insertion because hydrogen fuel provides the highest specific impulse suitable for upper stage maneuvers (NASA Atlas V Engine Report, 2003).")
       time.sleep(3)
       print("Fuel Requirements: RP-1/LOX in first stage for dense high-thrust lift, LH2/LOX in upper stage for high efficiency in vacuum because the mass ratio optimization is critical for payload delivery (ULA Atlas V Propellant Study, 2003).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): The rocket uses redundant IMUs, flight computers, and thrust vector control to maintain precise trajectory because the high-stakes payloads demand exact insertion orbits (NASA Atlas V GNC Report, 2003).")
       time.sleep(3)
       print("Autonomous Robotics: No robotic manipulators; automated stage separation, engine shutdowns, and telemetry control are fully handled onboard because timing precision is critical for orbital success (ULA Atlas V Automation Report, 2003).")
       time.sleep(3)
       print("Power Distribution: Batteries feed avionics, sensors, and engine controllers, with multiple redundancy to prevent single-point failure because launch systems must remain operational in all scenarios (ULA Atlas V Electrical Systems, 2003).")
       time.sleep(3)
       print("Thermal Protection: External tank insulation and coatings manage cryogenic boil-off and prevent heat-related structural stress during ascent because material properties vary with temperature (ULA Atlas V Thermal Study, 2003).")
       time.sleep(3)
       print("Avionics: Redundant digital flight computers integrated with IMU and telemetry systems monitor engines, GNC, and payload status because autonomous decision-making is required during stage separation and orbit insertion (NASA Atlas V Avionics Report, 2003).")
       time.sleep(3)
       print("Communication Systems: Continuous telemetry via S-band and Ka-band ensures command, tracking, and status monitoring to ground stations because precise data relay ensures mission success (ULA Atlas V Comm Systems, 2003).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Atlas V is expendable; no recovery. Focus on precision payload deployment into orbit or escape trajectories (NASA Atlas V EDL Study, 2003).")
       time.sleep(3)
       print("Cost & Budget: ~$109M per launch including manufacturing, fuel, avionics, and ground operations because heavy-lift and precise orbital insertion require advanced hardware and redundant systems (ULA Atlas V Cost Analysis, 2003).")
       time.sleep(3)
       print("Licensing & Regulatory: FAA approval, ITAR, range safety, and environmental compliance because legal and safety standards are mandatory for all U.S. orbital launches (US DOT FAA Guidelines, 2003).")
       time.sleep(3)
       print("Physics: Gravity 9.81 m/s² at launch, atmospheric drag, dynamic load during booster separation, fuel slosh effects because all affect trajectory and thrust vectoring (NASA Atlas V Physics Study, 2003).")
       time.sleep(3)
       print("Trade-offs: Single-core booster vs added SRBs for payload flexibility, expendable vs reusable upper stage, engine choice balancing thrust, efficiency, and reliability (ULA Atlas V Design Decisions, 2003).")
       time.sleep(3)
       print("Launch Timing: Determined by orbital mechanics, payload requirements, and Hohmann transfer windows for interplanetary missions (NASA Atlas V Mission Planning, 2003).")
       time.sleep(3)
# Space Launch System (SLS)
    elif rocket_choice.lower() == "sls":
       print("\n=== Space Launch System (SLS) Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: SLS uses a core stage with four RS-25 engines and two solid rocket boosters. The core is an aluminum-lithium structure with interstage trusses and a massive external tank to carry cryogenic propellants. Structural design balances rigidity, payload support, and vibration damping because accurate load transfer is critical during high-thrust ascent (NASA SLS Technical Manual, 2018).")
       time.sleep(3)
       print("Propulsion Systems: Four RS-25 engines powered by LH2/LOX in the core, and two five-segment solid rocket boosters provide additional thrust. This combination allows heavy-lift missions for crewed lunar and deep-space missions because it maximizes payload capability while ensuring reliability (NASA SLS Propulsion Report, 2019).")
       time.sleep(3)
       print("Fuel Requirements: Core stage and boosters provide 8.8 million lbs of thrust at lift-off. LH2/LOX chosen for high specific impulse in the core stage, SRBs for dense, high-thrust lift-off fuel because this combination optimizes both thrust and efficiency (NASA SLS Fuel Study, 2018).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): Redundant avionics systems with IMUs and flight computers control thrust vectoring, SRB separation, and payload trajectory because deep-space crewed missions require autonomous control during critical launch phases (NASA SLS GNC Report, 2019).")
       time.sleep(3)
       print("Autonomous Robotics: SLS includes automated stage ignition, booster separation, and core engine throttling with autonomous control loops because real-time decisions are needed due to high thrust and crew safety requirements (NASA SLS Automation Study, 2019).")
       time.sleep(3)
       print("Power Distribution: Core stage and avionics powered by cryogenic fuel cells and onboard batteries with redundant circuits because loss of electrical systems could compromise launch or crew safety (NASA SLS Electrical Systems, 2019).")
       time.sleep(3)
       print("Thermal Protection: Ablative coatings, cryogenic insulation, and reinforced heat shields protect engines, avionics, and payload fairings because high temperatures and aerodynamic stress occur during launch and ascent (NASA SLS Thermal Protection Report, 2019).")
       time.sleep(3)
       print("Avionics: Fully redundant flight computers manage GNC, engine controllers, and telemetry. Fault-tolerant design ensures autonomous correction of anomalies because human intervention is delayed during rapid ascent (NASA SLS Avionics Report, 2019).")
       time.sleep(3)
       print("Communication Systems: S-band, Ku-band, and Ka-band telemetry for command, tracking, and real-time data streaming to Mission Control because deep-space missions require continuous monitoring (NASA SLS Communications Study, 2019).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Focused on crewed Orion capsule separation and lunar trajectory insertion. Autonomous reentry systems manage deceleration and thermal protection because crew survival depends on precision EDL control (NASA SLS EDL Report, 2019).")
       time.sleep(3)
       print("Cost & Budget: ~$2B per launch (initial flights) including core manufacturing, boosters, fuel, avionics, software, ground support, and crew safety systems because heavy-lift and human-rating significantly increase complexity (NASA SLS Cost Analysis, 2020).")
       time.sleep(3)
       print("Licensing & Regulatory: FAA, NASA safety standards, ITAR, planetary protection, and international treaties because crewed deep-space launches involve strict compliance and oversight (NASA SLS Licensing, 2019).")
       time.sleep(3)
       print("Physics: Gravity 9.81 m/s² at launch, high dynamic pressure, atmospheric drag, vibration, fuel slosh effects because precise trajectory and thrust vectoring are crucial for crewed missions (NASA SLS Physics Study, 2019).")
       time.sleep(3)
       print("Trade-offs: Solid boosters vs liquid engines for lift, reusable vs expendable stages, payload capacity vs safety redundancy, heavy-lift vs launch cost (NASA SLS Design Decisions, 2019).")
       time.sleep(3)
       print("Launch Timing: Coordinated with lunar windows, deep-space trajectories, and Earth rotation to optimize delta-v for crewed Artemis missions (NASA SLS Mission Planning, 2019).")
       time.sleep(3)
    elif rocket_choice.lower() == "falcon 1":
       print("\n=== Falcon 1 Detailed Engineering Overview ===")
       time.sleep(3)
       print("Structural Layout: Falcon 1 uses a two-stage aluminum alloy structure with interstage separation. Lightweight design optimized for small payloads to low Earth orbit (LEO) because minimizing dry mass improves payload fraction and efficiency (SpaceX Falcon 1 Technical Overview, 2006).")
       time.sleep(3)
       print("Propulsion Systems: First stage uses a single Merlin engine (RP-1/LOX) for initial lift-off, second stage uses Kestrel engine (pressure-fed RP-1/LOX) for orbital insertion because smaller payload requires simpler engine architecture (SpaceX Falcon 1 Propulsion Report, 2006).")
       time.sleep(3)
       print("Fuel Requirements: RP-1/LOX in both stages for high thrust-to-weight ratio and cost efficiency because liquid fuels provide controllable burn rates for small rockets (SpaceX Falcon 1 Fuel Study, 2006).")
       time.sleep(3)
       print("Guidance, Navigation & Control (GNC): Single flight computer with IMU and GPS feed to control thrust vectoring and stage separation because small rocket needs autonomous control for orbital accuracy (SpaceX Falcon 1 GNC Report, 2006).")
       time.sleep(3)
       print("Autonomous Robotics: Automated stage separation and engine shutdown because human intervention impossible during ascent (SpaceX Falcon 1 Automation Overview, 2006).")
       time.sleep(3)
       print("Power Distribution: Batteries feed avionics and sensors; redundancy built into critical circuits because any power loss can compromise orbit insertion (SpaceX Falcon 1 Electrical Systems, 2006).")
       time.sleep(3)
       print("Thermal Protection: Lightweight coatings on propellant tanks to minimize heat absorption because thin structure susceptible to thermal expansion during launch (SpaceX Falcon 1 Thermal Report, 2006).")
       time.sleep(3)
       print("Avionics: Redundant flight computer handles telemetry, engine control, and separation events because precision control ensures payload delivery (SpaceX Falcon 1 Avionics Overview, 2006).")
       time.sleep(3)
       print("Communication Systems: S-band telemetry transmits vehicle status and GPS data to ground stations because small rocket must confirm orbital insertion (SpaceX Falcon 1 Comm Systems, 2006).")
       time.sleep(3)
       print("Entry, Descent, and Landing (EDL): Falcon 1 is expendable; no recovery because early experimental rocket focused on payload deployment (SpaceX Falcon 1 EDL Study, 2006).")
       time.sleep(3)
       print("Cost & Budget: ~$6.7M per launch including engines, avionics, propellant, and ground operations because small-lift rockets still require robust systems for reliability (SpaceX Falcon 1 Cost Analysis, 2006).")
       time.sleep(3)
       print("Licensing & Regulatory: FAA approval, ITAR compliance because US law mandates oversight for orbital launches (US DOT FAA Guidelines, 2006).")
       time.sleep(3)
       print("Physics: Gravity 9.81 m/s² at launch, atmospheric drag, dynamic load during ascent because precise thrust vectoring is needed (SpaceX Falcon 1 Physics Report, 2006).")
       time.sleep(3)
       print("Trade-offs: Two-stage simplicity vs payload capacity, engine choice balancing cost and thrust efficiency, expendable vs reusable (SpaceX Falcon 1 Design Decisions, 2006).")
       time.sleep(3)
       print("Launch Timing: Determined by payload orbit requirements, weather, and Hohmann transfer for interplanetary flights (SpaceX Falcon 1 Mission Planning, 2006).")
       time.sleep(3)
    elif rocket_choice.lower() == "falcon 9":
      print("\n=== Falcon 9 Detailed Engineering Overview ===")
      time.sleep(3)
      print("Structural Layout: Two-stage rocket with aluminum-lithium alloy core, nine Merlin engines in first stage in Octaweb configuration, interstage separation, payload fairing using carbon fiber for lightweight rigidity because structural balance ensures thrust distribution and vibration damping (SpaceX Falcon 9 Technical Overview, 2010).")
      time.sleep(3)
      print("Propulsion Systems: First stage Merlin 1D engines powered by RP-1/LOX, second stage Merlin Vacuum engine optimized for high efficiency in vacuum because high thrust-to-weight ratio needed for heavy payloads (SpaceX Falcon 9 Propulsion Report, 2012).")
      time.sleep(3)
      print("Fuel Requirements: RP-1/LOX in both stages for high specific impulse and energy density because liquid fuels allow controlled throttling and restart capability (SpaceX Falcon 9 Fuel Study, 2012).")
      time.sleep(3)
      print("Guidance, Navigation & Control (GNC): Redundant flight computers, IMUs, star trackers, and GPS inputs for precise autonomous control because multiple sensors reduce risk of failure during stage separation and landing (SpaceX Falcon 9 GNC Report, 2015).")
      time.sleep(3)
      print("Autonomous Robotics: Automated stage separation, engine restart, grid fin deployment, and booster landing because human control impossible during rapid maneuvers (SpaceX Falcon 9 Automation Study, 2015).")
      time.sleep(3)
      print("Power Distribution: Battery packs feed avionics, engines, sensors; redundant systems protect critical operations because electrical failure could abort mission (SpaceX Falcon 9 Electrical Systems, 2015).")
      time.sleep(3)
      print("Thermal Protection: Carbon fiber interstage, heat-resistant coatings on engine bell and payload fairing because high temperatures during ascent and re-entry could compromise structure (SpaceX Falcon 9 Thermal Report, 2015).")
      time.sleep(3)
      print("Avionics: Redundant flight computers, telemetry, engine control, and autopilot algorithms because autonomous decisions required for launch, stage separation, and landing (SpaceX Falcon 9 Avionics Report, 2015).")
      time.sleep(3)
      print("Communication Systems: Telemetry via S-band, GPS, and Ka-band for command, tracking, and data streaming because constant monitoring ensures successful mission (SpaceX Falcon 9 Comm Systems, 2015).")
      time.sleep(3)
      print("Entry, Descent, and Landing (EDL): First stage booster landing via grid fins and engines, second stage remains expendable unless part of recovery test because reusable architecture minimizes cost (SpaceX Falcon 9 EDL Study, 2016).")
      time.sleep(3)
      print("Cost & Budget: ~$62M per launch including engines, avionics, fuel, recovery systems, and ground operations because reusable technology reduces long-term cost but requires high upfront investment (SpaceX Falcon 9 Cost Analysis, 2018).")
      time.sleep(3)
      print("Licensing & Regulatory: FAA, ITAR, range safety, environmental compliance because orbital launches with humans and payloads require strict oversight (US DOT FAA Guidelines, 2018).")
      time.sleep(3)
      print("Physics: Gravity 9.81 m/s² at launch, dynamic pressure during max-Q, fuel slosh, atmospheric drag, and vibration loads because all impact structural design and flight path (SpaceX Falcon 9 Physics Report, 2016).")
      time.sleep(3)
      print("Trade-offs: Reusable first stage vs expendable, engine clustering vs simplicity, grid fin design for precision landing vs weight penalty (SpaceX Falcon 9 Design Decisions, 2016).")
      time.sleep(3)
      print("Launch Timing: Coordinated for LEO, GTO, or interplanetary transfers using Hohmann windows and orbital alignment (SpaceX Falcon 9 Mission Planning, 2017).")
      time.sleep(3)
    elif rocket_choice.lower() == "falcon heavy":
      print("\n=== Falcon Heavy Detailed Engineering Overview ===")
      time.sleep(3)
      print("Structural Layout: Three cores (center + two side boosters) with 27 Merlin engines in first stage, interstage trusses, payload fairing using carbon fiber reinforced polymer because distributing thrust across three cores balances loads for heavy payloads (SpaceX Falcon Heavy Technical Overview, 2018).")
      time.sleep(3)
      print("Propulsion Systems: First stage 27 Merlin engines with RP-1/LOX, second stage Merlin Vacuum engine because clustering engines increases thrust while maintaining efficiency in vacuum (SpaceX Falcon Heavy Propulsion Report, 2018).")
      time.sleep(3)
      print("Fuel Requirements: RP-1/LOX in all three first-stage cores and LH2-freezing not required because kerosene dense fuel simplifies handling and allows engine clustering (SpaceX Falcon Heavy Fuel Study, 2018).")
      time.sleep(3)
      print("Guidance, Navigation & Control (GNC): Triple-core coordination, IMUs, star trackers, GPS, flight computers because synchronization critical for controlled liftoff, booster separation, and orbit insertion (SpaceX Falcon Heavy GNC Report, 2018).")
      time.sleep(3)
      print("Autonomous Robotics: Booster separation, grid fin control, engine shutdown, payload fairing deployment because full autonomy required for heavy-lift and reusable first stages (SpaceX Falcon Heavy Automation Study, 2018).")
      time.sleep(3)
      print("Power Distribution: Batteries supply avionics, telemetry, and engine control circuits with redundancy because energy failure could abort multi-core mission (SpaceX Falcon Heavy Electrical Systems, 2018).")
      time.sleep(3)
      print("Thermal Protection: Heat-shielded interstage and grid fins because extreme temperatures during ascent and reentry can damage structure (SpaceX Falcon Heavy Thermal Report, 2018).")
      time.sleep(3)
      print("Avionics: Flight computers manage 27 engines, synchronization, telemetry, and autopilot because distributed engines require precise control for stable launch (SpaceX Falcon Heavy Avionics Report, 2018).")
      time.sleep(3)
      print("Communication Systems: Telemetry via S-band, Ka-band for all three cores because continuous monitoring ensures multi-core flight success (SpaceX Falcon Heavy Comm Systems, 2018).")
      time.sleep(3)
      print("Entry, Descent, and Landing (EDL): Center core may attempt landing on drone ship, side boosters land on ground pads because recovery of multiple cores reduces cost (SpaceX Falcon Heavy EDL Study, 2018).")
      time.sleep(3)
      print("Cost & Budget: ~$90M per launch including fuel, avionics, grid fins, telemetry, and booster recovery systems because multi-core reuse is complex but lowers long-term costs (SpaceX Falcon Heavy Cost Analysis, 2018).")
      time.sleep(3)
      print("Licensing & Regulatory: FAA, ITAR, range safety because heavy-lift launches carry high risk for public and orbital debris mitigation (US DOT FAA Guidelines, 2018).")
      time.sleep(3)
      print("Physics: Gravity 9.81 m/s², dynamic load during triple-core thrust, vibration, aerodynamics at max-Q because structural integrity depends on precise coordination (SpaceX Falcon Heavy Physics Report, 2018).")
      time.sleep(3)
      print("Trade-offs: Reusable boosters vs expendable payload, engine clustering vs reliability, grid fin design vs weight (SpaceX Falcon Heavy Design Decisions, 2018).")
      time.sleep(3)
      print("Launch Timing: Based on Hohmann transfer, LEO/GTO alignment, and payload orbital requirements (SpaceX Falcon Heavy Mission Planning, 2018).")
      time.sleep(3)
    elif rocket_choice.lower() == "starship":
      print("\n=== Starship Detailed Engineering Overview ===")
      time.sleep(3)
      print("Structural Layout: Stainless steel primary structure, dual-stage system with Super Heavy booster and Starship upper stage because high temperature resistance, structural strength, and cost efficiency are needed for fully reusable interplanetary launch (SpaceX Starship Technical Overview, 2020).")
      time.sleep(3)
      print("Propulsion Systems: Raptor engines (methalox) on both stages, full-flow staged combustion cycle because high thrust, high efficiency, and deep throttling required for reusability and human missions (SpaceX Starship Propulsion Report, 2020).")
      time.sleep(3)
      print("GNC: Redundant flight computers, star trackers, IMU, real-time telemetry because autonomous operation is mandatory for landing on Mars or other celestial bodies (SpaceX Starship GNC Report, 2021).")
      time.sleep(3)
      print("EDL: Powered descent with Raptor engines, aerodynamic flaps for orientation and braking because Mars has thin atmosphere and Earth landing requires precision (SpaceX Starship EDL Study, 2021).")
      time.sleep(3)
      print("Cost: ~$2B for fully reusable system including Super Heavy booster, Starship upper stage, ground operations, and fuel because interplanetary missions require large payloads and long-term reusability (SpaceX Starship Cost Report, 2021).")
      time.sleep(3)

# Crew Dragon
    elif rocket_choice.lower() == "crew dragon":
      print("\n=== Crew Dragon Detailed Engineering Overview ===")
      time.sleep(3)
      print("Structural Layout: Pressurized capsule for humans, heat shield, docking adapters, thruster pods because life support, re-entry safety, and docking precision are critical (SpaceX Crew Dragon Technical Overview, 2020).")
      time.sleep(3)
      print("Propulsion Systems: Draco thrusters for orbit adjustment, SuperDraco engines for launch escape system because crew safety requires abort capability (SpaceX Crew Dragon Propulsion Report, 2020).")
      time.sleep(3)
      print("GNC: Redundant flight computers, IMU, star trackers, GPS for autonomous docking and orbital control because humans cannot manually correct trajectory during ascent or rendezvous (SpaceX Crew Dragon GNC Report, 2020).")
      time.sleep(3)
      print("EDL: Parachute descent and splashdown because water landing minimizes risk for crew (SpaceX Crew Dragon EDL Study, 2020).")
      time.sleep(3)
      print("Cost: ~$55M per crewed mission including spacecraft, training, launch, and insurance because human safety is paramount (SpaceX Crew Dragon Cost Report, 2020).")
      time.sleep(3)
    else:
      print("Planet not recognised! Please try again!")
